Added port_channel and port_channel_member.
netascode/terraform-nxos-nac-nxos pull request #1
Opened 2024-12-19 01:23 UTC by tobiwang

2025-03-03 16:24 UTC, danischm requested changes

2025-03-03 16:24 UTC, danischm commented on nxos_interface.tf
> +	  vrf           = "default"
Shouldn't this be the VRF of the interface instead of hardcoded to "default"?

2025-03-04 08:39 UTC, tobiwang commented on nxos_interface.tf
> +	  vrf           = "default"
Hi Daniel, sorry for that. I have fixed line 260. Could you please review again? Thanks.

2025-03-05 08:16 UTC, danischm approved these changes

2025-03-05 08:16 UTC, merged